apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - htpasswd:
        fileData:
          name: htpasswd-users
      mappingMethod: claim
      name: htpasswd
      type: HTPasswd
