resources:
  - 1-openshift-serverless-namespace/ #resources for installing the operator in openshift-serverless namespace
  - 2-knative-serving-namespace/ #resources for installing knative-serving in knative-serving namespace

