apiVersion: v1
kind: Namespace
metadata:
  # needed for cert-manager resources such as webhooks, listeners, issuers, etc
  name: cert-manager
  labels:
    app.kubernetes.io/managed-by: openshift-gitops
    argocd.argoproj.io/managed-by: openshift-gitops