apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-cert-manager-clusterissuers-role
  annotations:
    argocd.argoproj.io/sync-wave: "4"
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["clusterissuers"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-cert-manager-clusterissuers-binding
  annotations:
    argocd.argoproj.io/sync-wave: "5"
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  kind: ClusterRole
  name: argocd-cert-manager-clusterissuers-role
  apiGroup: rbac.authorization.k8s.io