resources:
  - metallb-operator/
  - devspaces/
  - cert-manager/
  - pipelines/
  - openshiftai/
  # - servicemeshoperator3/ #used by openshiftai. - Disabled, new v3 operator of RHOAI installs a separate Service Mesh 3 operator even if current one is already installed.
  - serverless-operator/ #used by openshiftai

  # GPU enabling operators:
  - nodefeaturediscovery/
  - kernel-module-management/
  - amd-gpu-operator/