resources:
  - metallb-operator/
  - devspaces/
  - cert-manager/
  - pipelines/
  - openshiftai/
  - servicemeshoperator3/ #used by openshiftai
  - serverless-operator/ #used by openshiftai

  # GPU enabling operators:
  - nodefeaturediscovery/
  - kernel-module-management/
  - amd-gpu-operator/