apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: pipelines-sub
  namespace: openshift-pipelines
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  name: openshift-pipelines-operator-rh
  channel: latest
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace