# Parent/Root argocd Application for the App of Apps pattern: https://argo-cd.readthedocs.io/en/latest/operator-manual/cluster-bootstrapping/#app-of-apps-pattern
# This application deploys/manages all other applications defined in the gitops/app-of-apps directory.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: openshift-gitops
spec:
  project: tailscale
  source:
    repoURL: https://github.com/MooseStack/tailscale_helm.git
    targetRevision: main
    path: tailscale
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/managed-by: openshift-gitops
        argocd.argoproj.io/managed-by: openshift-gitops
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: "*"
      kind: "Application"
      jsonPointers:
        # Allow manually disabling auto sync for apps, useful for debugging.
        - /spec/syncPolicy/automated
        # These are automatically updated on a regular basis. Not ignoring last applied configuration since it's used for computing diffs after normalization.
        - /metadata/annotations/argocd.argoproj.io~1refresh
        - /operation
    - group: ""
      kind: Secret
      name: tailscale-secret
      jsonPointers:
          - /data