apiVersion: v1
kind: Namespace
metadata:
  # needed to place it in openshift-operators due to operator constraints
  name: openshift-operators
  labels:
    app.kubernetes.io/managed-by: openshift-gitops
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"