apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: web-terminal-sub
  namespace: openshift-web-terminal
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  name: web-terminal
  channel: fast
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace