apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshiftai-sub
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  name: rhods-operator
  channel: stable
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace