#v3 of RHOAI operator.
kind: DataScienceCluster
apiVersion: datasciencecluster.opendatahub.io/v2
metadata:
  name: default-dsc
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app.kubernetes.io/name: datasciencecluster
spec:
  components:
    modelmeshserving:
      managementState: Managed
    dashboard:
      managementState: Managed
    aipipelines:
      managementState: Managed
    feastoperator:
      managementState: Managed
    kserve:
      managementState: Managed
      serving:
        managementState: Unmanaged
    llamastackoperator:
      managementState: Removed
    kueue:
      managementState: Removed
    mlflowoperator:
      managementState: Removed
    modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries
    ray:
      managementState: Managed
    workbenches:
      managementState: Managed
    trainingoperator:
      managementState: Managed
    trustyai:
      managementState: Managed
